### PR TITLE
Feat (bpdm-certificate-management) - Added API to check whether a provided BPN is certified for a specific certificate type

### PR DESCRIPTION
**Pull request by alexsilva-CGI**
## Description

This PR adds a API that validates if the certificate is trusted or not.
Contributes to #3
Should be merged only after #28

## Pre-review checks

Please ensure to do as many of the following checks as possible, before asking for committer review:

- [x] DEPENDENCIES are up-to-date. [Dash license tool](https://github.com/eclipse/dash-licenses). Committers can open IP issues for restricted libs.
- [x] [Copyright and license header](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02) are present on all affected files

### CODE REVIEW

**Review by nicoprow — COMMENTED** [review]
I read the requirements for this use case so I checked the CertificateDb entity. The trust levels are typed as String there but the issue clearly enumerates an exhaustive list of trust levels. Therefoere I would make an enum class for the trust level and change the entity field from String to that enum type.

**Review by nicoprow — COMMENTED** [review]
Since I had some doubts about what is being done here I checked the issue and asked for some clarification there. Maybe you can help me out understanding the requirements behinde this better:

https://github.com/eclipse-tractusx/bpdm-certificate-management/issues/3#issuecomment-1865579927

**Comment by SujitMBRDI** [comment]
> Since I had some doubts about what is being done here I checked the issue and asked for some clarification there. Maybe you can help me out understanding the requirements behinde this better:
> 
> [#3 (comment)](https://github.com/eclipse-tractusx/bpdm-certificate-management/issues/3#issuecomment-1865579927)

@nicoprow, I hope comment on issue is sorted. I have refactored code a bit.
Please take a look and suggest we missed anything here

**Review by nicoprow — COMMENTED** [review]
I don't see what has changed regading to my concerns.

I doubt whether such a simple certificate endpoint is needed at all. The principle of having a field which indicates whether the certificate actually exists is also not very RESTful. It is more usual to just use a 404 in that regard.

Why not just use the existing endpoint for fulfulling this feature?

Anyway, if that's how it should be, the code itself looks fine to me

**Comment by SujitMBRDI** [comment]
> I don't see what has changed regading to my concerns.
> 
> I doubt whether such a simple certificate endpoint is needed at all. The principle of having a field which indicates whether the certificate actually exists is also not very RESTful. It is more usual to just use a 404 in that regard.
> 
> Why not just use the existing endpoint for fulfulling this feature?
> 
> Anyway, if that's how it should be, the code itself looks fine to me

@nicoprow, I didn't changed anything regarding your concern. I agree, this endpoint doesn't make any sense once we have as we have already handled same scenario with 404 in other endpoint.

I kept requirement as it is and developed endpoint. So, in future once i receive confirmation on need of endpoint so i can either deprecate it or keep it.

**Review by nicoprow — APPROVED** [review]

**Pull request merged**
